 @url_dev = http://localhost:3056/v1/api

POST {{url_dev}}/shop/signup
Content-Type: application/json 
x-api-key: 734b19461f4e14f0df06bf3886bbe6dac5b6606a260c426289c9caa6726c2420f00d4fd02fce17bb8a771422d3935bbf50bbe6e42784e35083563cc77aa5cc28

{
    "email": "14",
    "password": "1"
}

###

POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: 734b19461f4e14f0df06bf3886bbe6dac5b6606a260c426289c9caa6726c2420f00d4fd02fce17bb8a771422d3935bbf50bbe6e42784e35083563cc77aa5cc28

{
    "email": "14",
    "password": "1"
}

###
POST {{url_dev}}/shop/update_verify/6479a1c5f7eea24100662fa8
Content-Type: application/json
x-api-key: 30929e75539a12a71ea783896b3b99f6d93e78ab41a820ae7e5a3477c520b1fbc6205681dd9f3c2f5950177c233ce246d1df8579f2ba091a303f19cb66c99282


###
POST {{url_dev}}/vnpay/create_payment_url
Content-Type: application/json
x-api-key: 734b19461f4e14f0df06bf3886bbe6dac5b6606a260c426289c9caa6726c2420f00d4fd02fce17bb8a771422d3935bbf50bbe6e42784e35083563cc77aa5cc28
x-client-id: 6479a1c5f7eea24100662fa8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDc5YTFjNWY3ZWVhMjQxMDA2NjJmYTgiLCJlbWFpbCI6IjEyMTIiLCJpYXQiOjE2OTg2NTI2NDksImV4cCI6MTY5ODgyNTQ0OX0.FHYPlpTDTTFqIij0Fzso3cd4xe0ERIExRu5mMwtdq9Q

{
        "amount": "100",
        "language": "vn",
        "bankCode": ""
}
0
###
POST {{url_dev}}/transaction/deleteProduct
Content-Type: application/json
x-api-key: 734b19461f4e14f0df06bf3886bbe6dac5b6606a260c426289c9caa6726c2420f00d4fd02fce17bb8a771422d3935bbf50bbe6e42784e35083563cc77aa5cc28
x-client-id: 6479a1c5f7eea24100662fa8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDc5YTFjNWY3ZWVhMjQxMDA2NjJmYTgiLCJlbWFpbCI6IjEyMTIiLCJpYXQiOjE2OTg2NTI2NDksImV4cCI6MTY5ODgyNTQ0OX0.FHYPlpTDTTFqIij0Fzso3cd4xe0ERIExRu5mMwtdq9Q

{
    "userId" : "64799ce7f7eea24100662fa3",
     "newCartData": [{"_id":"653880051e94550bfcd6c49c",
     "product_name":"sản phẩm 1",
     "product_thumb":"https://res.cloudinary.com/dvqmndx5j/image/upload/v1697453955/banhang/omnjogruvon1h9eecen2.jpg","product_description":"đẹp","product_price":100,"product_quantity":100,
     "product_type":"Electronics",
     "product_shop":"647e985dfc08161cc7e7f7da",
     "product_attributes":
     {"manufacturer":"quy","color":"đỏ","size":"l"},
     "product_ratingsAverage":4.5,
     "product_variations":[],
     "isPublished":true,
     "createdAt":"2023-10-25T02:40:05.355Z",
     "updatedAt":"2023-10-25T02:40:05.355Z",
     "product_slug":"san-pham-1","__v":0,
     "quantity":2}]
}


###
POST {{url_dev}}/product/delete/646f52c65caeac0dd7587af2
Content-Type: application/json
x-api-key: 025ce9a805c109871ed8664bea8a8e5403f162daf9d7bfd220b4aee6683993350483959b54538db3dc220fa426f334c9e740c66e068cc9ab03318ab4426f606b
x-client-id: 645f78f0ff400061f37e430d
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDVmNzhmMGZmNDAwMDYxZjM3ZTQzMGQiLCJlbWFpbCI6IjEyMTIiLCJpYXQiOjE2ODUwMjUzNTUsImV4cCI6MTY4NTE5ODE1NX0.T6mj2OTNpaKHNjFJ70n_2mE_bdntDlg7IIGbtJV1x5s

###
Get {{url_dev}}/users/userId/647e985dfc08161cc7e7f7da
Content-Type: application/json
x-api-key: 30929e75539a12a71ea783896b3b99f6d93e78ab41a820ae7e5a3477c520b1fbc6205681dd9f3c2f5950177c233ce246d1df8579f2ba091a303f19cb66c99282
x-client-id: 647e911bdc92e18f3fcc4c5b
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDdlOTExYmRjOTJlMThmM2ZjYzRjNWIiLCJlbWFpbCI6IjEiLCJpYXQiOjE2ODYwMTgyNzUsImV4cCI6MTY4NjE5MTA3NX0.g52r9TkcTelv5LWZRe7LJmSN9VGRm5qtMt9ljjQFul8

###
post {{url_dev}}/users/update/64799ce7f7eea24100662fa3
Content-Type: application/json
x-api-key: 30929e75539a12a71ea783896b3b99f6d93e78ab41a820ae7e5a3477c520b1fbc6205681dd9f3c2f5950177c233ce246d1df8579f2ba091a303f19cb66c99282
x-client-id: 647e911bdc92e18f3fcc4c5b
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDdlOTExYmRjOTJlMThmM2ZjYzRjNWIiLCJlbWFpbCI6IjEiLCJpYXQiOjE2ODYwNDAxOTgsImV4cCI6MTY4NjIxMjk5OH0.-pK735fCN67RTpHJMuV2CzUJ-UMZ_sZg5TlrIcEpG_o

###
POST {{url_dev}}/product/getAll
Content-Type: application/json
x-api-key: f84252040ba6025b2f4331140dd4e7f05387b18c92413b3c3633ecafaa84abccff87d11c14f6c125fda106033bd0458f2dc2b62532e07aaad3538050d0b983c3
x-client-id: 64eff56c094acda5b55a41fc
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGVmZjU2YzA5NGFjZGE1YjU1YTQxZmMiLCJlbWFpbCI6IjEyMTIiLCJpYXQiOjE2OTM1NTYzMjcsImV4cCI6MTY5MzcyOTEyN30.SAy-YBrobm8nt1o0181gsy5b23VgoB_fC8ygCJAPhb0

###
get {{url_dev}}/product/search/a
Content-Type: application/json
x-api-key: f84252040ba6025b2f4331140dd4e7f05387b18c92413b3c3633ecafaa84abccff87d11c14f6c125fda106033bd0458f2dc2b62532e07aaad3538050d0b983c3
x-client-id: 64eff56c094acda5b55a41fc
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGVmZjU2YzA5NGFjZGE1YjU1YTQxZmMiLCJlbWFpbCI6IjEyMTIiLCJpYXQiOjE2OTM1NTYzMjcsImV4cCI6MTY5MzcyOTEyN30.SAy-YBrobm8nt1o0181gsy5b23VgoB_fC8ygCJAPhb0


###
POST {{url_dev}}/product
Content-Type: application/json
x-api-key: f84252040ba6025b2f4331140dd4e7f05387b18c92413b3c3633ecafaa84abccff87d11c14f6c125fda106033bd0458f2dc2b62532e07aaad3538050d0b983c3
x-client-id: 64eff56c094acda5b55a41fc
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGVmZjU2YzA5NGFjZGE1YjU1YTQxZmMiLCJlbWFpbCI6IjEyMTIiLCJpYXQiOjE2OTM1NTYzMjcsImV4cCI6MTY5MzcyOTEyN30.SAy-YBrobm8nt1o0181gsy5b23VgoB_fC8ygCJAPhb0

{
    "product_name": "a3",
    "product_thumb": "https://scontent.fhan14-2.fna.fbcdn.net/v/t39.30808-6/328709559_1481611285700057_6150010650656469516_n.jpg?_nc_cat=108&ccb=1-7&_nc_sid=730e14&_nc_ohc=fmx6JHWykFEAX9Se7u7&_nc_ht=scontent.fhan14-2.fna&oh=00_AfCqbWGZIlu7d3XAuwFNBUBWxf0vzb52J0ccINks73Wd1g&oe=64739334", 
    "product_description": "aa",
    "product_price": 300,
    "product_type": "Electronics",
    "product_quantity": 5,
    "product_attributes": {
        "manufacturer": "quy",
        "size": "L",
        "color": "Denim"
}
}

###
patch {{url_dev}}/product/64f19e8149652c6eb8e16acb
Content-Type: application/json
x-api-key: f84252040ba6025b2f4331140dd4e7f05387b18c92413b3c3633ecafaa84abccff87d11c14f6c125fda106033bd0458f2dc2b62532e07aaad3538050d0b983c3
x-client-id: 64eff56c094acda5b55a41fc
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGVmZjU2YzA5NGFjZGE1YjU1YTQxZmMiLCJlbWFpbCI6IjEyMTIiLCJpYXQiOjE2OTM1NTYzMjcsImV4cCI6MTY5MzcyOTEyN30.SAy-YBrobm8nt1o0181gsy5b23VgoB_fC8ygCJAPhb0

{
    "product_name": "test101",
    "product_thumb": "123a", 
    "product_description": "aa",
    "product_price": 600,
    "product_type": "Electronics",
    "product_quantity": 5,
    "product_attributes": {
        "manufacturer": "quy",
        "size": "L",
        "color": "Denim"
}
}

###
get {{url_dev}}/cart/shopId/645f78f0ff400061f37e430d
Content-Type: application/json
x-api-key: 025ce9a805c109871ed8664bea8a8e5403f162daf9d7bfd220b4aee6683993350483959b54538db3dc220fa426f334c9e740c66e068cc9ab03318ab4426f606b
x-client-id: 645f78f0ff400061f37e430d
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDVmNzhmMGZmNDAwMDYxZjM3ZTQzMGQiLCJlbWFpbCI6IjEyMTIiLCJpYXQiOjE2ODUwNzI0ODcsImV4cCI6MTY4NTI0NTI4N30.ZTVjO1czM7Cu9YMJN15ESeliDS0PeKo3gVuCPmaFZR8


###
post {{url_dev}}/cart/getlist
Content-Type: application/json
x-api-key: 734b19461f4e14f0df06bf3886bbe6dac5b6606a260c426289c9caa6726c2420f00d4fd02fce17bb8a771422d3935bbf50bbe6e42784e35083563cc77aa5cc28
x-client-id: 65308eb09c28b53767e92f00
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTMwOGViMDljMjhiNTM3NjdlOTJmMDAiLCJlbWFpbCI6IjE0IiwiaWF0IjoxNzAwMTg3MTkxLCJleHAiOjE3MDAzNTk5OTF9.22C6zS_UdJP2tSJyGrrGua4diZEl_-yzoq9FSk60XpQ

{
    "userId": "65308eb09c28b53767e92f00"
}

###
post {{url_dev}}/cart
Content-Type: application/json
x-api-key: f84252040ba6025b2f4331140dd4e7f05387b18c92413b3c3633ecafaa84abccff87d11c14f6c125fda106033bd0458f2dc2b62532e07aaad3538050d0b983c3
x-client-id: 64f011633263a1cc56078926
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGYwMTE2MzMyNjNhMWNjNTYwNzg5MjYiLCJlbWFpbCI6IjEyMSIsImlhdCI6MTY5Mzc0OTQxOCwiZXhwIjoxNjkzOTIyMjE4fQ.RpIOLFN4rJG6gTFrnySeUGVQgRoOIEH6Vh5sb55Gp7o

{
    "userId": "64f14697f15478225387a2c2"
}


###
post {{url_dev}}/cart
Content-Type: application/json
x-api-key: f84252040ba6025b2f4331140dd4e7f05387b18c92413b3c3633ecafaa84abccff87d11c14f6c125fda106033bd0458f2dc2b62532e07aaad3538050d0b983c3
x-client-id: 64f14697f15478225387a2c2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGYxNDY5N2YxNTQ3ODIyNTM4N2EyYzIiLCJlbWFpbCI6IjEiLCJpYXQiOjE2OTM3MzEyMzUsImV4cCI6MTY5MzkwNDAzNX0._A-bgO-A6BJ0J3aai5RoPFni47Qg8zrSjDL7-9uEO1Y

{
       "userId": "645f77c72b38802e12f7b580",
       "shopId": "645f78f0ff400061f37e430d",
        "product" : {
        "productId": "646f535f5caeac0dd7587b17",
        "product_name": "test101",
        "product_thumb": "123a", 
        "product_description": "aa",
        "product_price": 600,
        "product_type": "Electronics",
        "product_attributes": {
            "manufacturer": "quy",
            "size": "L",
            "color": "Denim"
        },
        "quantity": 1

    }
}

###
get {{url_dev}}/transaction/shopId/64799ce7f7eea24100662fa3
Content-Type: application/json
x-api-key: 30929e75539a12a71ea783896b3b99f6d93e78ab41a820ae7e5a3477c520b1fbc6205681dd9f3c2f5950177c233ce246d1df8579f2ba091a303f19cb66c99282
x-client-id: 64799ce7f7eea24100662fa3
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDc5OWNlN2Y3ZWVhMjQxMDA2NjJmYTMiLCJlbWFpbCI6IjEyMSIsImlhdCI6MTY4NzE4NTcyOSwiZXhwIjoxNjg3MzU4NTI5fQ.GUDiPZ5nOFheZkKfMCx4Fhc-ePJZlAz-SnvSfUgo1Rc


###
post {{url_dev}}/transaction
Content-Type: application/json
x-api-key: 734b19461f4e14f0df06bf3886bbe6dac5b6606a260c426289c9caa6726c2420f00d4fd02fce17bb8a771422d3935bbf50bbe6e42784e35083563cc77aa5cc28
x-client-id: 647e911bdc92e18f3fcc4c5b
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDdlOTExYmRjOTJlMThmM2ZjYzRjNWIiLCJlbWFpbCI6IjEiLCJpYXQiOjE2OTgxNjAyMDYsImV4cCI6MTY5ODMzMzAwNn0.iojUA8imd3FD5m3qPqnB9AakSd3KWlBN6cm4NzDofpk

{
       "user": {
        "userId": "645f77c72b38802e12f7b580",
        "name": "test"
       },
        "product" : {
        "productId": "646f535f5caeac0dd7587b17",
        "product_name": "test101",
        "product_thumb": "123a", 
        "product_description": "aa",
        "product_price": 600,
        "product_type": "Electronics",
        "product_attributes": {
            "manufacturer": "quy",
            "size": "L",
            "color": "Denim"
        },
        "quantity": 1

    }
}

###
post {{url_dev}}/cart/update
Content-Type: application/json
x-api-key: 30929e75539a12a71ea783896b3b99f6d93e78ab41a820ae7e5a3477c520b1fbc6205681dd9f3c2f5950177c233ce246d1df8579f2ba091a303f19cb66c99282
x-client-id: 64799ce7f7eea24100662fa3
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDc5OWNlN2Y3ZWVhMjQxMDA2NjJmYTMiLCJlbWFpbCI6IjEyMSIsImlhdCI6MTY4Nzg3NTYzNCwiZXhwIjoxNjg4MDQ4NDM0fQ.tFZdU7I_19csom3R87n1Jss87jLVSIMSA3Jj0bBlVG8

{
       "userId": "6479a1c5f7eea24100662fa8",
        "shop_order_ids": [
            {
                "shopId": "64799ce7f7eea24100662fa3",
                "productId": "647ad9b7a2683e7833372790",
        "quantity": 5,
            "old_quantity": 2
            }
        ]
}

###
post {{url_dev}}/cart/delete
Content-Type: application/json
x-api-key: f84252040ba6025b2f4331140dd4e7f05387b18c92413b3c3633ecafaa84abccff87d11c14f6c125fda106033bd0458f2dc2b62532e07aaad3538050d0b983c3
x-client-id: 64f011633263a1cc56078926
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGYwMTE2MzMyNjNhMWNjNTYwNzg5MjYiLCJlbWFpbCI6IjEyMSIsImlhdCI6MTY5Mzc0OTQxOCwiZXhwIjoxNjkzOTIyMjE4fQ.RpIOLFN4rJG6gTFrnySeUGVQgRoOIEH6Vh5sb55Gp7o

{
       "userId": "64f14697f15478225387a2c2",
        "productId": "64f19e8149652c6eb8e16acb"
}


###
get {{url_dev}}/product/byId/64f19e8149652c6eb8e16acb
Content-Type: application/json
x-api-key: f84252040ba6025b2f4331140dd4e7f05387b18c92413b3c3633ecafaa84abccff87d11c14f6c125fda106033bd0458f2dc2b62532e07aaad3538050d0b983c3
x-client-id: 64eff56c094acda5b55a41fc
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGVmZjU2YzA5NGFjZGE1YjU1YTQxZmMiLCJlbWFpbCI6IjEyMTIiLCJpYXQiOjE2OTM1NTYzMjcsImV4cCI6MTY5MzcyOTEyN30.SAy-YBrobm8nt1o0181gsy5b23VgoB_fC8ygCJAPhb0

# {
#     "product_name": "test100",
#     "product_thumb": "123a", 
#     "product_description": "aa",
#     "product_price": 600,
#     "product_type": "Electronics",
#     "product_quantity": 5,
#     "product_attributes": {
#         "manufacturer": "quy",
#         "size": "L",
#         "color": "Denim"
# }
# }


###
GET  {{url_dev}}/product/published/all
Content-Type: application/json
x-api-key: 30929e75539a12a71ea783896b3b99f6d93e78ab41a820ae7e5a3477c520b1fbc6205681dd9f3c2f5950177c233ce246d1df8579f2ba091a303f19cb66c99282
x-client-id: 6479a1c5f7eea24100662fa8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDc5YTFjNWY3ZWVhMjQxMDA2NjJmYTgiLCJlbWFpbCI6IjEyMTIiLCJpYXQiOjE2ODczNjUxMjQsImV4cCI6MTY4NzUzNzkyNH0.NwN6xD1YWGm7cl6K8vOmk6EB0NSijs20KVxrbeRak8g



###
GET  {{url_dev}}/product/1
Content-Type: application/json
x-api-key: 30929e75539a12a71ea783896b3b99f6d93e78ab41a820ae7e5a3477c520b1fbc6205681dd9f3c2f5950177c233ce246d1df8579f2ba091a303f19cb66c99282


###
Post  {{url_dev}}/product/publish/64f1a327f45a98598afb8644
Content-Type: application/json
x-api-key: f84252040ba6025b2f4331140dd4e7f05387b18c92413b3c3633ecafaa84abccff87d11c14f6c125fda106033bd0458f2dc2b62532e07aaad3538050d0b983c3
x-client-id: 64eff56c094acda5b55a41fc
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGVmZjU2YzA5NGFjZGE1YjU1YTQxZmMiLCJlbWFpbCI6IjEyMTIiLCJpYXQiOjE2OTM1NTYzMjcsImV4cCI6MTY5MzcyOTEyN30.SAy-YBrobm8nt1o0181gsy5b23VgoB_fC8ygCJAPhb0


###
POST {{url_dev}}/shop/logout
Content-Type: application/json
x-api-key: 7e62ced24b8f30277602cdd2b1df03c7236c3e5df9a81d52f00368f9e6e16bcc4a77d537826e43242c4c6875233346e98caebd994566319c505f39cd13381690
x-client-id: 6419277499ba5446034cae8d
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE5Mjc3NDk5YmE1NDQ2MDM0Y2FlOGQiLCJlbWFpbCI6ImN1b25nQGdtYWlsLmNvbSIsImlhdCI6MTY3OTUzNzM3NywiZXhwIjoxNjc5NzEwMTc3fQ.g2Fo-0jB6eIV39xj6ccUP6nVmvYwO2Puq0u18G3cO3M


